I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/swipe.rpy", line 44, in script call
    call choice
  File "game/scripts/swipe.rpy", line 44, in script call
    call choice
ScriptError: could not find label 'choice'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/swipe.rpy", line 44, in script call
    call choice
  File "/Users/aljo/Downloads/5y1s/psych 180/renpy-8.2.0-sdk/renpy/ast.py", line 1416, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/scripts/swipe.rpy", line 44, in script call
    call choice
  File "/Users/aljo/Downloads/5y1s/psych 180/renpy-8.2.0-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'choice'.

macOS-15.0.1-arm64-arm-64bit arm64
Ren'Py 8.2.0.24012702
Simmer 1.0
Thu Oct 31 22:41:05 2024
